
stages:
  data_ingestion:
    cmd: python src/mlproject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlproject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip


  data_validation:
    cmd: python src/mlproject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlproject/pipeline/stage_02_data_validation.py
      - config/config.yaml

    outs:
      - artifacts/data_validation


  data_transformation:
    cmd: python src/mlproject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlproject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/data.zip

    outs:
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv


  training:
    cmd: python src/mlproject/pipeline/stage_04_model_training.py
    deps:
      - src/mlproject/pipeline/stage_04_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/data.zip
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

    outs:
      - artifacts/model_trainer/model.joblib


  evaluation:
    cmd: python src/mlproject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlproject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/data.zip
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/model_trainer/model.joblib
    
    outs:
      - artifacts/model_evaluation/metrics.json
